spring.application.name=Ferreteria

# UTF-8 Global Encoding Configuration
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.sql.init.encoding=UTF-8
spring.thymeleaf.encoding=UTF-8

# Base de Datos H2 en Memoria (Ejecución instantánea sin dependencias)
spring.datasource.url=jdbc:h2:mem:ferreteriadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true

# Para producción / SQL Server local:
# spring.datasource.url=jdbc:sqlserver://localhost;instanceName=DEV;databaseName=FERRETERIA;encrypt=true;trustServerCertificate=true;
# spring.datasource.username=sa
# spring.datasource.password=sql
# spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080